<?php

// autoload.php @generated by php-scoper

// Load ClassLoader first
require_once __DIR__ . '/composer/ClassLoader.php';

// Load the real autoloader
require_once __DIR__ . '/composer/autoload_real.php';

// Return the loader instance
return ESIG_Vendor\ComposerAutoloaderInit8b52da00066833e649f197f577790273::getLoader();
